# Generated by Django 5.2 on 2025-05-12 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="日期")),
                (
                    "confirmed_count",
                    models.IntegerField(default=0, verbose_name="确诊总数"),
                ),
                (
                    "suspected_count",
                    models.IntegerField(default=0, verbose_name="疑似总数"),
                ),
                (
                    "cured_count",
                    models.IntegerField(default=0, verbose_name="治愈总数"),
                ),
                ("dead_count", models.IntegerField(default=0, verbose_name="死亡总数")),
                (
                    "confirmed_incr",
                    models.IntegerField(default=0, verbose_name="新增确诊"),
                ),
                (
                    "suspected_incr",
                    models.IntegerField(default=0, verbose_name="新增疑似"),
                ),
                ("cured_incr", models.IntegerField(default=0, verbose_name="新增治愈")),
                ("dead_incr", models.IntegerField(default=0, verbose_name="新增死亡")),
            ],
            options={
                "verbose_name": "每日全国统计",
                "verbose_name_plural": "每日全国统计",
            },
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="省份名称")),
                (
                    "short_name",
                    models.CharField(max_length=20, verbose_name="省份简称"),
                ),
                (
                    "confirmed_count",
                    models.IntegerField(default=0, verbose_name="确诊人数"),
                ),
                (
                    "suspected_count",
                    models.IntegerField(default=0, verbose_name="疑似病例"),
                ),
                (
                    "cured_count",
                    models.IntegerField(default=0, verbose_name="治愈人数"),
                ),
                ("dead_count", models.IntegerField(default=0, verbose_name="死亡人数")),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                ("data_date", models.DateField(verbose_name="数据日期")),
            ],
            options={
                "verbose_name": "省份疫情数据",
                "verbose_name_plural": "省份疫情数据",
                "unique_together": {("name", "data_date")},
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="城市名称")),
                (
                    "confirmed_count",
                    models.IntegerField(default=0, verbose_name="确诊人数"),
                ),
                (
                    "suspected_count",
                    models.IntegerField(default=0, verbose_name="疑似病例"),
                ),
                (
                    "cured_count",
                    models.IntegerField(default=0, verbose_name="治愈人数"),
                ),
                ("dead_count", models.IntegerField(default=0, verbose_name="死亡人数")),
                ("data_date", models.DateField(verbose_name="数据日期")),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="covid_data.province",
                        verbose_name="所属省份",
                    ),
                ),
            ],
            options={
                "verbose_name": "城市疫情数据",
                "verbose_name_plural": "城市疫情数据",
                "unique_together": {("province", "name", "data_date")},
            },
        ),
    ]
